# Generic
UNPROCESS_ENTITY = 'UNPROCESS_ENTITY'
INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
INVALID_REQUEST = 'INVALID_REQUEST'
FILE_NOT_FOUND = 'FILE_NOT_FOUND'
INVALID_FILE_DATA = 'INVALID_FILE_DATA'
INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'

# EduLens specific
PDF_INGESTION_FAILED = 'PDF_INGESTION_FAILED'
VIDEO_INGESTION_FAILED = 'VIDEO_INGESTION_FAILED'
EMBEDDING_FAILED = 'EMBEDDING_FAILED'
RETRIEVAL_FAILED = 'RETRIEVAL_FAILED'
LLM_GENERATION_FAILED = 'LLM_GENERATION_FAILED'
SAFETY_CHECK_FAILED = 'SAFETY_CHECK_FAILED'
CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND'
INVALID_GRADE_LEVEL = 'INVALID_GRADE_LEVEL'